/*
 * Personal Finance Management API
 *
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIPMF.Models
{ 
        /// <summary>
        /// Debit (`d`) for liabilities or credit (`c`) for assets
        /// </summary>
        /// <value>Debit (`d`) for liabilities or credit (`c`) for assets</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DirectionsEnum
        {
            /// <summary>
            /// Enum DEnum for d
            /// </summary>
            [EnumMember(Value = "d")]
            DEnum = 0,
            /// <summary>
            /// Enum CEnum for c
            /// </summary>
            [EnumMember(Value = "c")]
            CEnum = 1        }
}
