/*
 * Personal Finance Management API
 *
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIPMF.Models
{ 
        /// <summary>
        /// Ascending or descending sort order
        /// </summary>
        /// <value>Ascending or descending sort order</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SortOrderEnum
        {
            /// <summary>
            /// Enum AscEnum for asc
            /// </summary>
            [EnumMember(Value = "asc")]
            AscEnum = 0,
            /// <summary>
            /// Enum DescEnum for desc
            /// </summary>
            [EnumMember(Value = "desc")]
            DescEnum = 1        }
}
