/*
 * Personal Finance Management API
 *
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIPMF.Models
{ 
    /// <summary>
    ///  
    /// </summary>
    [DataContract]
    public partial class SpendingInCategory : IEquatable<SpendingInCategory>
    { 
        /// <summary>
        /// Code of the category
        /// </summary>
        /// <value>Code of the category</value>

        [DataMember(Name="catcode")]
        public string Catcode { get; set; }

        /// <summary>
        /// Amount spent in category
        /// </summary>
        /// <value>Amount spent in category</value>

        [DataMember(Name="amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// Number of transactions included in group
        /// </summary>
        /// <value>Number of transactions included in group</value>

        [DataMember(Name="count")]
        public decimal? Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpendingInCategory {\n");
            sb.Append("  Catcode: ").Append(Catcode).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SpendingInCategory)obj);
        }

        /// <summary>
        /// Returns true if SpendingInCategory instances are equal
        /// </summary>
        /// <param name="other">Instance of SpendingInCategory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpendingInCategory other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Catcode == other.Catcode ||
                    Catcode != null &&
                    Catcode.Equals(other.Catcode)
                ) && 
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) && 
                (
                    Count == other.Count ||
                    Count != null &&
                    Count.Equals(other.Count)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Catcode != null)
                    hashCode = hashCode * 59 + Catcode.GetHashCode();
                    if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                    if (Count != null)
                    hashCode = hashCode * 59 + Count.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SpendingInCategory left, SpendingInCategory right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SpendingInCategory left, SpendingInCategory right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
