/*
 * Personal Finance Management API
 *
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace APIPMF.Models
{ 
    /// <summary>
    ///  
    /// </summary>
    [DataContract]
    public partial class TransactionCategorizeCommand : IEquatable<TransactionCategorizeCommand>
    { 
        /// <summary>
        /// Code of category or subcategory to move transaction to
        /// </summary>
        /// <value>Code of category or subcategory to move transaction to</value>
        [Required]

        [DataMember(Name="catcode")]
        public string Catcode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionCategorizeCommand {\n");
            sb.Append("  Catcode: ").Append(Catcode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TransactionCategorizeCommand)obj);
        }

        /// <summary>
        /// Returns true if TransactionCategorizeCommand instances are equal
        /// </summary>
        /// <param name="other">Instance of TransactionCategorizeCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionCategorizeCommand other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Catcode == other.Catcode ||
                    Catcode != null &&
                    Catcode.Equals(other.Catcode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Catcode != null)
                    hashCode = hashCode * 59 + Catcode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TransactionCategorizeCommand left, TransactionCategorizeCommand right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TransactionCategorizeCommand left, TransactionCategorizeCommand right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
