/*
 * Personal Finance Management API
 *
 * Personal Finance Management API allows analyze of a client's spending patterns against pre-defined budgets over time 
 *
 * OpenAPI spec version: v1
 * Contact: aleksandar.milosevic@asseco-see.rs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using APIPMF.Models;

namespace APIPMF.Database.Entities
{ 
   
    public class TransactionEntity
    {
        private Transaction transaction;

        public TransactionEntity(Transaction transaction)
        {
            this.transaction = transaction;
        }

        [Required]

        [DataMember(Name="id")]
        public string Id { get; private set; }

      

        [DataMember(Name="beneficiary-name")]
        public string BeneficiaryName { get; set; }

       
        [Required]

        [DataMember(Name="date")]
        public string Date { get; set; }

   
        [Required]

        [DataMember(Name="direction")]
        public DirectionsEnum Direction { get; set; }

        
        [Required]

        [DataMember(Name="amount")]
        public double? Amount { get; set; }


        [DataMember(Name="description")]
        public string Description { get; set; }

        
        [Required]

        [StringLength(3, MinimumLength=3)]
        [DataMember(Name="currency")]
        public string Currency { get; set; }


        [DataMember(Name="mcc")]
        public MccCodeEnum Mcc { get; set; }

        
        [Required]

        [DataMember(Name="kind")]
        public TransactionKindsEnum Kind { get; set; }


        [DataMember(Name="catcode")]
        public string Catcode { get; private set; }

 
    }
}
